# Generated by Django 3.1.1 on 2020-09-23 17:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(choices=[('BP', 'Breathing Problem'), ('DC', 'Dry Cough'), ('ST', 'Sore Throat'), ('W', 'Weakness'), ('RN', 'Runny Nose')], max_length=255)),
                ('additionalInformation', multiselectfield.db.fields.MultiSelectField(choices=[('AP', 'Abdominal Pain'), ('V', 'Vomiting'), ('D', 'Diarrhea'), ('CP', 'Chest Pain'), ('P', 'Chest Pressure'), ('MP', 'Muscle Pain'), ('LT', 'Loss Of Taste'), ('LS', 'Loss Of Smell'), ('RS', 'Rash On The Skin'), ('DF', 'Discoloration Of Fingers'), ('DT', 'Discoloration Of Toes'), ('LS', 'Loss Of Speech'), ('LM', 'Loss Of Movement')], max_length=255)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
